// Generates api/_lib/fortuneEngine.js from src/utils/fortuneEngine.ts so the serverless daily-fortune email
// runs the exact same engine as the site. The engine is a pure file (no imports), so a plain transpile is enough.
// Run automatically at the start of `npm run build`; commit the regenerated file when the engine changes.
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import ts from 'typescript';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const srcPath = path.join(root, 'src/utils/fortuneEngine.ts');
const outPath = path.join(root, 'api/_lib/fortuneEngine.js');

const source = fs.readFileSync(srcPath, 'utf-8');
if (/^\s*import\s/m.test(source)) {
  console.error('❌ fortuneEngine.ts must stay import-free for build-engine.js (add a bundler step if it needs imports).');
  process.exit(1);
}

const { outputText } = ts.transpileModule(source, {
  compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2022, removeComments: false }
});

const banner = '// GENERATED by scripts/build-engine.js from src/utils/fortuneEngine.ts. Do not edit by hand.\n';
fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, banner + outputText, 'utf-8');
console.log('✅ Generated api/_lib/fortuneEngine.js from src/utils/fortuneEngine.ts');
